spring.application.name=kikidiliveryApi

spring.datasource.url=jdbc:postgresql://localhost:5433/kikidilivery
spring.datasource.username=kikidilivery
spring.datasource.password=kikidilivery
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
